### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'run')

### ISSUE THREAD

**Issue by wiselancer** [e2b-dev/fragments#69]
Hi guys. having an issue with the initializing sandbox. Is there anyone who can give an advice?
userID undefined
apiKey undefined
Created sandbox undefined
 ⨯ TypeError: Cannot read properties of undefined (reading 'run')
    at POST (/Users/wiselancer/dev/fragments/.next/server/chunks/app_api_sandbox_route_ts_987268._.js:51:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /Users/wiselancer/dev/fragments/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55759
    at async eO.execute (/Users/wiselancer/dev/fragments/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46527)
    at async eO.handle (/Users/wiselancer/dev/fragments/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57093)
    at async doRender (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/base-server.js:1345:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/base-server.js:1475:28)
    at async DevServer.renderPageComponent (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/base-server.js:1901:24)
    at async DevServer.renderToResponseImpl (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/base-server.js:1939:32)
    at async DevServer.pipeImpl (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/base-server.js:914:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/base-server.js:810:17)
    at async /Users/wiselancer/dev/fragments/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/wiselancer/dev/fragments/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/Users/wiselancer/dev/fragments/node_modules/next/dist/server/lib/start-server.js:141:13)
 POST /api/sandbox 500 in 1306ms
<img width="2408" alt="Screenshot 2024-10-06 at 6 20 59 PM" src="https://github.com/user-attachments/assets/b2c057e8-cc76-49cd-94c9-09781f197726">

**Comment by wiselancer** [comment]
![Uploading Screenshot 2024-10-06 at 6.30.08 PM.png…]()

**Comment by wiselancer** [comment]
<img width="961" alt="Screenshot 2024-10-06 at 6 30 08 PM" src="https://github.com/user-attachments/assets/82210566-8e52-4cc0-89c1-163cd6d3f518">

**Comment by mishushakov** [comment]
I was unable to reproduce, closing this - feel free to reopen if you are still experiencing the issue
